[package]
name = "localref-client"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
localref_core = { package = "localref-core", path = "../core" }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
axum = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
