[package]
name = "csc"
version = "0.1.0"
edition = "2024"
autobins = false

[features]
default = []
desktop = []
native-tray = ["desktop"]

[dependencies]
axum = { workspace = true }
http = { workspace = true }
localref_core = { package = "localref-core", path = "../core" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tower = { workspace = true }
